### ISSUE TITLE
Possible to add MERGE support?

### ISSUE THREAD

**Issue by motherlymuppet** [brettwooldridge/SansOrm#10]
It seems pretty simple to add H2's merge function to OrmWriter, but it's a right pain to add it externally.

Is there a reason why it's absent at the minute?

**Comment by brettwooldridge** [comment]
So far we have avoided and post SQL99 constructs because of limited support by various databases.  Merge/upsert support would require dialect specific extensions.  For example, PostgreSQL uses an entirely different syntax.

**Comment by brettwooldridge** [comment]
Pull requests are welcome but should be as comprehensive as possible. For example, detecting database version and behaving accordingly, or throwing a NotImplementedException.
