### ISSUE TITLE
BigDecimal -> Double conversion

### ISSUE THREAD

**Issue by NicolaIsotta** [brettwooldridge/SansOrm#36]
Hello, is there any reason why BigDecimal is not converted to Double if `fieldType == Double.class`?

https://github.com/brettwooldridge/SansOrm/blob/bfb16aa380202b9204205313dd0beb48df735952/src/main/java/com/zaxxer/sansorm/internal/Introspected.java#L234-L244

**Comment by brettwooldridge** [comment]
@NicolaIsotta Seems like an oversight.  Pull requests welcome.
