### ISSUE TITLE
Problematic license in Introspector.java

### ISSUE THREAD

**Issue by emilianbold** [brettwooldridge/SansOrm#9]
Hello,

I was planning on using this library but then stumbled upon:

```src/main/java/com/zaxxer/sansorm/internal/Introspector.java``` which has this copyright header:

```
/*
 * The contents of this file are proprietary and may not be
 * modified or distributed in source or compiled form without
 * express written permission from the copyright holders.
 *
 * Copyright 2008-2011, DancerNetworks
 * All rights reserved.
 */
```

Everything else seems to be Apache 2.

**Comment by brettwooldridge** [comment]
Ha!  The perils of IDE code templates mixed with comment-folding.  We'll fix it.
